//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;

namespace tms_machines_base
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineCharacteristic
    {
        public int MachineID { get; set; }
        public Nullable<decimal> DiameterMax { get; set; }
        public Nullable<decimal> LengthMax { get; set; }
        public string Magazin { get; set; }
        public string Turret { get; set; }
        public string Images { get; set; }
    
        public virtual Machine Machine { get; set; }
    }
}
